services:
  - type: web
    name: chouxuan-data-meteor-rain
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: FEISHU_APP_ID
        sync: false
      - key: FEISHU_APP_SECRET
        sync: false
      - key: FEISHU_FOLDER_TOKEN
        sync: false
      - key: FEISHU_OAUTH_SCOPE
        sync: false
      - key: FEISHU_REDIRECT_URI
        sync: false
